#166879999 Users should be able to rate articles
andela/ah-frontend-kronos pull request #19
Opened 2019-07-24 13:28 UTC by Manorlds-Eaglespark

#### What does this PR do?
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2019-07-26 08:57 UTC, reifred requested changes
Thanks @Manorlds-Eaglespark for the work done. However, I got an error after rating an article maybe you should consider correcting this.
![image](https://user-images.githubusercontent.com/22131999/61939467-024efa00-af9c-11e9-8bcd-4d139b895644.png)

2019-07-26 08:57 UTC, reifred commented on src/actions/articles/rating/rateArticleAction.js
> +const lastPart = '/rate';
I think we have url connections file that stores the url there is no need to declare the url again.

2019-07-26 08:57 UTC, reifred commented on src/actions/articles/rating/updateRatingAction.js
> +const lastPart = '/rate';
The same at this point don't re-declare the url

2019-07-26 09:22 UTC, Manorlds-Eaglespark commented
> Thanks @Manorlds-Eaglespark for the work done. However, I got an error after rating an article maybe you should consider correcting this.
> ![image](https://user-images.githubusercontent.com/22131999/61939467-024efa00-af9c-11e9-8bcd-4d139b895644.png)

You could try refreshing your browser.

2019-07-26 09:24 UTC, reifred commented
> > Thanks @Manorlds-Eaglespark for the work done. However, I got an error after rating an article maybe you should consider correcting this.
> > ![image](https://user-images.githubusercontent.com/22131999/61939467-024efa00-af9c-11e9-8bcd-4d139b895644.png)
> 
> You could try refreshing your browser.

I did kindly look into it and notify me when it is solved

2019-07-26 09:33 UTC, Manorlds-Eaglespark commented
> > > Thanks @Manorlds-Eaglespark for the work done. However, I got an error after rating an article maybe you should consider correcting this.
> > > ![image](https://user-images.githubusercontent.com/22131999/61939467-024efa00-af9c-11e9-8bcd-4d139b895644.png)
> > 
> > 
> > You could try refreshing your browser.
> 
> I did kindly look into it and notify me when it is solved

Sure, alright.

2019-08-01 14:44 UTC, Manorlds-Eaglespark commented
> > > > Thanks @Manorlds-Eaglespark for the work done. However, I got an error after rating an article maybe you should consider correcting this.
> > > > ![image](https://user-images.githubusercontent.com/22131999/61939467-024efa00-af9c-11e9-8bcd-4d139b895644.png)
> > > 
> > > 
> > > You could try refreshing your browser.
> > 
> > 
> > I did kindly look into it and notify me when it is solved
> 
> Sure, alright.

I have done something to address this. Though it is not in the scope of this feature. Thanks.

2019-08-02 12:27 UTC, reifred approved these changes
Thanks for the good work done @Manorlds-Eaglespark

2019-08-02 12:41 UTC, Rhytah approved these changes

2019-08-02 15:06 UTC, kcharles52 approved these changes

2019-08-02 15:06 UTC, merged